{% set name = "artificial-adversary" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/airbnb/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f6f2824d24465ebd2b84ceb8975cbed90f5e51ede8d32640da6ede1e6b083742

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas
    - nltk
    - textblob

test:
  imports:
    - Adversary

about:
  home: https://github.com/airbnb/artificial-adversary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  dev_url: https://github.com/airbnb/artificial-adversary

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
